### ISSUE TITLE
when will version 5 bootstrap support be published?

### ISSUE THREAD

**Issue by nsra** [PerseusTheGreat/bootstrap-rtl-npm-scss#3]
when will version 5 bootstrap support be published? are you working on it! does it seem to take a long time!!

**Comment by PerseusTheGreat** [comment]
The official Bootstrap 5.x is RTL capable and is supporting by main community (since [May 5th 2021](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/)), so I have not any plan for it.

Take a look at this:
[Bootstrao 5.x official package on NPM](https://www.npmjs.com/package/bootstrap
)
